spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mini_bank
    username: kodilla_user
    password: kodilla_password
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false
      database: mysql